<a href="https://colab.research.google.com/github/palaksharma-2005/summer-internship/blob/main/practice_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world

In [ ]:
#variabes:
name = "palak"
age = 22
print(name)
print(age)

palak
22

In [ ]:
#taking input from input :
name = input("enter your name")
print("hello",name)

enter your namepalak
hello palak

In [ ]:
#typecasting
age = 23.56
print(int(age))

marks = 23
print(float(marks))

23
23.0

In [ ]:
#conditional statments:

In [ ]:
#practice questions:

In [ ]:
#pandas library :
#one dimensional data:
import pandas as pd
marks = pd.Series([23 , 45 ,56 , 57 , 34])
print(marks)

0    23
1    45
2    56
3    57
4    34
dtype: int64

In [ ]:
#multidimensional array:
student = {"name": ["palak","rahul","mohan"],
           }

In [ ]:
#loading data from csv and excel:
df = pd.read_csv("Zomato-data-.csv")

In [ ]:
df.sample(4) #give random data

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
15,Cafe Vivacity,Yes,No,3.8/5,90,650,Cafes
125,Soms Kitchen & Bakes,No,No,2.9/5,0,400,Dining
139,Aramane Donne Biriyani,No,No,2.9/5,0,150,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,0,350,Dining

In [ ]:
df.head() #give 5 rows

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.shape #rows and column

(148, 7)

In [ ]:
df.dtypes #about the datatypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [ ]:
df.describe() #mean median count max min

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [ ]:
df[["name" , "online_order"]] #multiple columns

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df["name"] #particular column

0                      Jalsa
1             Spice Elephant
2            San Churro Cafe
3      Addhuri Udupi Bhojana
4              Grand Village
               ...
143         Melting Melodies
144          New Indraprasta
145             Anna Kuteera
146                   Darbar
147            Vijayalakshmi
Name: name, Length: 148, dtype: object

In [ ]:

df[(df['listed_in(type)'] == 'Dining') & (df['book_table'] =='Yes') ] #outer df for conditioning and inner df for accesing that columns

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
61,Goa 0 Km,Yes,Yes,3.6,163,800,Dining
63,Jeet Restaurant,No,Yes,4.0,808,850,Dining

In [ ]:
df.sort_values("votes", ascending=False) #for descending ascending = false

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,4.4,4884,750,other
86,Meghana Foods,Yes,No,4.4,4401,600,Dining
7,Onesta,Yes,Yes,4.6,2556,600,Cafes
44,Onesta,Yes,Yes,4.6,2556,600,other
65,Kabab Magic,Yes,No,4.1,1720,400,Dining
...,...,...,...,...,...,...,...
140,Darkolates,No,No,3.3,0,200,Dining
143,Melting Melodies,No,No,3.3,0,100,Dining
142,Gawdaru Mane Beriyani,No,No,3.3,0,300,Dining
141,Swaada Healthy Kitchen,No,No,3.3,0,350,Dining
144,New Indraprasta,No,No,3.3,0,150,Dining

In [ ]:
df.rename(columns={"name": "customer_name"}  )
df.rename(columns={"name": "customer_name"} , inplace=True )


 #changing the column name and inplace for permanent change of the name

In [ ]:
df['votes'].isnull().sum() #to check and count if there is any columns have null vales

np.int64(0)